TRUNCATE NaughtyNice, ElvenWorkers, CurrentToys, ToyHistory CASCADE;

insert into NaughtyNice (childName, childAge, naughty) values ('Goldy Bachshell', 6, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Clarabelle Raffeorty', 1, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Currie Chaunce', 4, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Dick Gummery', 9, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Krishnah Posten', 3, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Hunfredo Pilipets', 9, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Moyra MacPhee', 4, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Elaina Bullman', 5, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Willi Rack', 5, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Mersey Sweeten', 4, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Bernie Wheater', null, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Adrien Vequaud', 4, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Liz Ackrill', 10, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Chicky Wicklin', 9, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Jaquenette Christol', 10, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Haroun Engledow', 3, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Jobie Sage', 10, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Idelle Spikins', 9, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Jonathan Canape', 9, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Thorn Ryhorovich', 8, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Teodoro Cooksey', 10, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Zackariah Casterou', null, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Ethe Cretney', 3, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Dasie Bromehead', 5, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Kurt Ellyatt', 10, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Lela O''Carrol', 4, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Georg Lownds', 1, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Udall Attridge', 3, true);
insert into NaughtyNice (childName, childAge, naughty) values ('Anetta Pirozzi', 3, false);
insert into NaughtyNice (childName, childAge, naughty) values ('Britt Cronk', 2, true);

insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Ashley Batrick', null, 'Junior Toymaker', 1, 189);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Lesli Alyoshin', 27, 'Senior Toymaker', 3, 81);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Winston Lauchlan', null, 'Toymaking Intern', 1, 67);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Inger Daburn', 36, 'Assistant Toymaker', 1, 299);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Stearn Bickerton', 25, 'Assistant Toymaker', 3, 112);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Bella Ygoe', 36, 'Toymaking Intern', 2, 124);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Kimberley Glitherow', null, 'Toymaking Intern', 1, 210);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Fleming Lumsdale', 37, 'Toymaking Intern', 2, 220);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Miriam Hallitt', null, 'Assistant Toymaker', 3, 285);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Morgun Convery', 24, 'Toymaking Intern', 1, 186);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Barbey End', 26, 'Senior Toymaker', 3, 216);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Marysa Ivers', 27, 'Assistant Toymaker', 2, 178);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Pammie Moat', null, 'Assistant Toymaker', 1, 148);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Merci Mullis', 35, 'Toymaking Intern', 2, 116);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Jilleen Pickin', 39, 'Junior Toymaker', 1, 255);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Julieta Birchner', 27, 'Assistant Toymaker', 3, 67);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Ilse Harvie', 24, 'Toymaking Intern', 2, 163);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Ange Bedinham', 35, 'Toymaking Intern', 3, 221);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Orsola Voase', 35, 'Assistant Toymaker', 1, 201);
insert into ElvenWorkers (elvenName, elvenAge, positionName, shiftNumber, numProducedToys) values ('Eolanda Winborn', null, 'Toymaking Intern', 1, 46);

insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('est risus', 'Khaki', 2.9, 15, 2);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('magna ac', 'Green', 4.5, 9, 20);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('id', 'Khaki', 2.0, 24, 17);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('sagittis', 'Turquoise', 3.4, 1, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('etiam', 'Pink', 3.0, 11, 8);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('non', 'Violet', 2.9, 27, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ultricies', 'Yellow', 4.5, 4, 20);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('in', null, 4.0, 24, 2);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('amet eros', 'Green', 2.4, 10, 10);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('at feugiat', 'Purple', 1.5, 6, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('diam nam', 'Mauv', 3.4, 21, 17);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('odio', 'Green', 4.2, 15, 5);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('suspendisse', 'Green', 4.6, 19, 17);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('enim', 'Yellow', 2.2, 14, 12);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('in', 'Red', 3.0, 28, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('eget', 'Yellow', 1.5, 20, 9);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('faucibus accumsan', 'Indigo', 3.2, 30, 10);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('cras non', 'Indigo', 1.2, 23, 10);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('lobortis est', 'Indigo', 4.3, 19, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('porta', 'Turquoise', 2.0, 19, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('aliquam', 'Red', 4.4, 22, 5);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('sem', 'Yellow', 2.1, 7, 7);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('vel est', 'Crimson', 3.2, 15, 18);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ultrices phasellus', 'Orange', 4.9, 16, 9);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ullamcorper augue', 'Blue', 2.9, 21, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('accumsan felis', 'Pink', 2.4, 16, 5);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('sociis', 'Mauv', 4.5, 4, 7);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('lobortis sapien', 'Yellow', 3.0, 11, 9);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('est phasellus', 'Khaki', 2.7, 24, 12);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('laoreet', 'Turquoise', 4.4, 15, 5);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('etiam pretium', null, 1.3, 25, 19);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('etiam', 'Orange', 4.2, 23, 14);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ultrices', 'Maroon', 3.7, 16, 10);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('at nibh', 'Teal', 3.6, 18, 1);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('nulla tempus', 'Blue', 1.0, 5, 19);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('in sapien', 'Maroon', 3.9, 18, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('fermentum donec', 'Fuscia', 2.0, 9, 15);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('augue', 'Violet', 2.0, 19, 19);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('odio', 'Goldenrod', 1.0, 10, 1);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('viverra', 'Khaki', 3.8, 21, 3);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('nulla elit', 'Violet', 3.4, 1, 9);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('lectus', 'Goldenrod', 4.5, 4, 17);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('morbi', 'Aquamarine', 3.6, 26, 5);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('tristique', 'Mauv', 4.0, 19, 11);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('mauris', 'Yellow', 4.0, 26, 7);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('lacus', 'Puce', 2.4, 6, 18);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('pede', 'Violet', 0.8, 10, 9);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('est quam', 'Fuscia', 1.4, 18, 6);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('nulla', 'Maroon', 2.3, 28, 15);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('molestie', 'Indigo', 2.0, 25, 20);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('nulla pede', 'Violet', 2.6, 24, 17);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('morbi porttitor', 'Khaki', 3.6, 20, 2);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('in libero', 'Puce', 4.5, 14, 7);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('nisl', 'Turquoise', 1.6, 21, 9);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('fusce', 'Pink', 1.9, 8, 20);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('eleifend', 'Yellow', 3.8, 14, 20);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ultrices libero', 'Red', 1.3, 8, 1);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('id', 'Aquamarine', 3.6, 20, 14);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('nibh', 'Violet', 4.3, 17, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('justo', 'Indigo', 3.1, 18, 9);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('sed', null, 2.4, 9, 11);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('mattis', 'Khaki', 4.8, 1, 12);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('vitae', 'Purple', 3.1, 24, 18);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('imperdiet nullam', 'Green', 2.6, 27, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('suscipit', null, 3.7, 10, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('feugiat', null, 2.8, 27, 12);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('dolor', 'Puce', 2.6, 16, 13);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('volutpat sapien', 'Teal', 1.8, 8, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('vitae', 'Blue', 4.6, 29, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('odio cras', 'Mauv', 4.1, 1, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('aliquet', 'Yellow', 0.5, 26, 15);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('tempor', 'Turquoise', 3.0, 4, 3);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('vestibulum ante', 'Indigo', 3.6, 26, 16);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('lacinia', 'Turquoise', 1.8, 10, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ultrices', 'Turquoise', 2.8, 28, 13);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('at dolor', 'Red', 4.7, 6, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('velit donec', 'Puce', 3.0, 3, 7);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('habitasse', 'Aquamarine', 4.6, 21, 3);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('eget tincidunt', 'Crimson', 1.3, 5, 4);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('et', 'Orange', 3.3, 6, 11);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('tellus nulla', 'Pink', 0.9, 18, 6);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('magna ac', 'Indigo', 4.2, 10, 14);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('vulputate', 'Red', 3.4, 24, 7);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('in', 'Maroon', 5.0, 10, 10);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('quam pede', 'Fuscia', 3.0, 14, 19);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ultrices vel', 'Teal', 2.8, 23, 19);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('quam a', 'Violet', 0.8, 4, 19);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('sed magna', 'Blue', 1.1, 30, 1);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('sit', null, 3.5, 4, 15);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('tortor eu', 'Puce', 2.4, 30, 17);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('convallis', 'Blue', 3.1, 20, 18);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('felis', null, 2.8, 7, 1);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('feugiat et', 'Aquamarine', 0.9, 10, 13);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('ut', 'Blue', 2.2, 11, 11);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('curabitur in', 'Turquoise', 2.2, 20, 8);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('mi pede', 'Purple', 1.0, 17, 3);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('vestibulum aliquet', 'Fuscia', 3.0, 14, 7);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('libero', null, 4.4, 20, 12);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('elit', 'Crimson', 2.0, 15, 17);
insert into CurrentToys (toyName, toyColor, workTime, childID, elvenID) values ('amet diam', 'Indigo', 1.8, 29, 13);

insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('duis at', 'Mauv', 1.9, 22, 1, 2012, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('justo sollicitudin', 'Mauv', 2.6, 23, 1, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sociis', 'Green', 4.6, 9, 17, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aliquam quis', 'Green', 0.9, 11, 11, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eget vulputate', 'Crimson', 4.0, 26, 15, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('turpis sed', 'Maroon', 3.7, 27, 10, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('pulvinar', 'Goldenrod', 3.3, 22, 8, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nunc', null, 1.7, 30, 3, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('pulvinar', 'Turquoise', 0.8, 27, 12, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('morbi', 'Aquamarine', 4.1, 13, 3, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('feugiat et', 'Teal', 3.1, 20, 1, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('et', 'Blue', 2.3, 23, 8, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ligula in', 'Purple', 3.7, 2, 3, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('posuere felis', 'Yellow', 4.9, 9, 4, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eget', 'Aquamarine', 3.8, 21, 2, 2012, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('consequat', 'Maroon', 0.8, 18, 7, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('justo sit', 'Goldenrod', 3.9, 3, 15, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ligula pellentesque', 'Red', 4.9, 16, 9, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id pretium', 'Blue', 4.1, 15, 13, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in', 'Yellow', 3.0, 11, 14, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aenean', null, 2.4, 28, 20, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mauris', 'Turquoise', 1.3, 2, 7, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in consequat', 'Red', 1.2, 7, 17, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ipsum', 'Maroon', 4.0, 29, 11, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in tempor', 'Aquamarine', 1.9, 7, 19, 2012, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('orci luctus', 'Puce', 1.0, 11, 5, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('tortor', 'Red', 2.9, 17, 12, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('urna pretium', null, 4.7, 4, 18, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sit', 'Orange', 4.4, 15, 17, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id', 'Aquamarine', 1.2, 23, 9, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('felis', 'Fuscia', 2.6, 25, 14, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id ligula', 'Orange', 3.5, 18, 16, 2014, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('elit ac', 'Turquoise', 2.8, 22, 19, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in lacus', 'Green', 2.2, 27, 6, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('cursus vestibulum', 'Goldenrod', 0.5, 21, 2, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id turpis', 'Turquoise', 3.1, 30, 14, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sapien', 'Puce', 1.4, 2, 14, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('quam sollicitudin', 'Maroon', 2.4, 30, 2, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('maecenas', 'Yellow', 4.1, 17, 2, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in leo', 'Maroon', 1.7, 24, 3, 2012, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('rhoncus mauris', 'Goldenrod', 2.1, 26, 7, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('congue', 'Khaki', 2.8, 12, 2, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('lorem', 'Puce', 3.3, 9, 7, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sit', 'Puce', 4.2, 9, 10, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nunc purus', 'Red', 4.0, 17, 16, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('est et', 'Khaki', 3.0, 9, 19, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('erat tortor', 'Teal', 2.3, 9, 8, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('at turpis', 'Green', 2.1, 21, 9, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eu', 'Red', 3.5, 4, 20, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ac lobortis', 'Indigo', 1.2, 3, 2, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('platea', 'Teal', 2.6, 12, 8, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mus', 'Khaki', 3.7, 4, 3, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('posuere cubilia', 'Fuscia', 4.2, 16, 1, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('pellentesque', 'Violet', 4.1, 14, 7, 2016, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('at lorem', null, 4.3, 26, 4, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id', 'Orange', 2.2, 13, 15, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('molestie', 'Green', 4.0, 29, 13, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('cursus urna', 'Green', 1.0, 23, 6, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sed sagittis', 'Khaki', 3.0, 15, 19, 2016, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ultrices posuere', 'Blue', 3.1, 15, 20, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nam', 'Blue', 4.9, 6, 19, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('velit vivamus', 'Yellow', 0.9, 30, 6, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nam', 'Green', 3.2, 23, 4, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nunc', 'Fuscia', 4.1, 1, 8, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mauris', 'Blue', 0.7, 10, 11, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('semper', 'Orange', 4.0, 9, 12, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sapien cursus', 'Green', 4.3, 30, 20, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in', 'Violet', 3.9, 27, 5, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aliquet', 'Red', 4.5, 19, 18, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('posuere', 'Orange', 4.1, 30, 13, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sapien ut', 'Khaki', 2.5, 19, 12, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mauris vulputate', 'Fuscia', 3.5, 22, 17, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nam', 'Crimson', 1.0, 30, 13, 2014, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('consequat lectus', 'Yellow', 4.4, 26, 13, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('tortor', 'Pink', 1.2, 5, 7, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('a pede', 'Puce', 3.6, 4, 15, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('tempus', 'Pink', 2.8, 29, 18, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('enim', 'Maroon', 2.2, 13, 9, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('a', 'Teal', 5.0, 8, 4, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nisl', null, 0.7, 11, 15, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mi integer', 'Yellow', 1.4, 14, 2, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('rhoncus', 'Orange', 2.3, 7, 4, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aliquet massa', 'Turquoise', 4.2, 28, 16, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('metus', 'Aquamarine', 1.0, 19, 11, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aliquet pulvinar', 'Violet', 3.2, 17, 11, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('cubilia curae', 'Purple', 0.8, 18, 17, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('non mauris', 'Pink', 1.1, 10, 18, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vitae nisl', 'Green', 1.9, 15, 19, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('justo', 'Green', 4.7, 23, 2, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vel', 'Pink', 2.2, 11, 18, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('dui vel', 'Puce', 3.9, 5, 16, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vehicula', 'Teal', 2.1, 11, 10, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('tortor', 'Purple', 1.9, 3, 19, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in', 'Puce', 1.4, 22, 16, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('consectetuer', 'Teal', 1.3, 23, 13, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id', 'Crimson', 2.5, 5, 11, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('libero nam', 'Aquamarine', 3.1, 9, 3, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('etiam pretium', 'Violet', 4.2, 16, 10, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id pretium', 'Red', 0.9, 23, 18, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('erat quisque', 'Blue', 3.2, 7, 6, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nibh', 'Orange', 0.8, 18, 1, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('convallis', 'Crimson', 2.9, 24, 9, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sapien cum', 'Khaki', 3.5, 28, 10, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eros', 'Blue', 2.7, 15, 2, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('primis', 'Turquoise', 3.0, 19, 12, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('blandit nam', 'Indigo', 1.5, 22, 9, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mi nulla', null, 0.6, 12, 4, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('phasellus id', 'Fuscia', 1.0, 25, 10, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('scelerisque', 'Teal', 4.9, 26, 12, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aliquam lacus', 'Khaki', 3.9, 28, 19, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vel pede', null, 0.6, 26, 20, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('pede', 'Puce', 1.5, 26, 16, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nisl', 'Turquoise', 3.9, 22, 4, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('lectus', 'Khaki', 2.0, 10, 20, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eget congue', 'Purple', 3.4, 12, 3, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('morbi', null, 3.9, 7, 18, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eget elit', 'Goldenrod', 1.4, 10, 7, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in faucibus', 'Goldenrod', 1.4, 15, 7, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('duis bibendum', 'Goldenrod', 4.7, 5, 15, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('amet consectetuer', 'Violet', 3.5, 13, 2, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('semper', 'Violet', 1.8, 8, 3, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vitae consectetuer', 'Khaki', 1.7, 28, 10, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('consequat dui', 'Indigo', 1.1, 11, 19, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ullamcorper purus', 'Maroon', 1.5, 27, 4, 2016, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vulputate elementum', 'Yellow', 0.8, 24, 19, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('lorem vitae', 'Yellow', 4.5, 23, 12, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('hac habitasse', 'Green', 2.0, 8, 18, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aliquet', 'Maroon', 2.4, 18, 1, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aenean sit', 'Mauv', 4.2, 15, 3, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vitae mattis', 'Aquamarine', 3.4, 13, 5, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sed', 'Maroon', 3.0, 26, 5, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('at nunc', 'Pink', 2.8, 22, 14, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('venenatis non', 'Maroon', 2.7, 17, 14, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('libero nullam', 'Yellow', 4.5, 13, 20, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('massa id', 'Green', 2.2, 29, 9, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('dolor sit', 'Khaki', 3.7, 12, 12, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('congue', 'Aquamarine', 1.0, 29, 17, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('erat id', 'Blue', 4.5, 25, 14, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('consectetuer adipiscing', 'Yellow', 4.9, 8, 3, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('erat', null, 4.3, 17, 15, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('et', 'Blue', 0.6, 11, 11, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('integer', 'Crimson', 4.9, 15, 11, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('felis fusce', 'Goldenrod', 3.2, 19, 19, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nec euismod', 'Violet', 2.1, 7, 12, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sit amet', 'Violet', 1.1, 7, 15, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('integer', 'Yellow', 2.6, 20, 2, 2016, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vel', 'Violet', 3.3, 18, 7, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vestibulum', 'Yellow', 3.2, 12, 1, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ac leo', 'Aquamarine', 1.1, 26, 4, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eget tempus', null, 2.9, 2, 4, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('montes nascetur', 'Goldenrod', 2.6, 23, 1, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('erat', 'Aquamarine', 2.1, 5, 14, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('suspendisse potenti', 'Purple', 2.5, 6, 7, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ante', 'Yellow', 2.4, 15, 4, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('viverra', 'Aquamarine', 3.6, 20, 4, 2016, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mauris enim', 'Indigo', 3.3, 26, 19, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('et', 'Khaki', 2.9, 17, 1, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mus vivamus', 'Blue', 3.4, 16, 5, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nullam', 'Fuscia', 3.0, 30, 11, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('hendrerit', 'Violet', 2.8, 13, 1, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vulputate', 'Fuscia', 4.9, 24, 19, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('tincidunt', 'Green', 2.1, 14, 15, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('diam', 'Turquoise', 3.2, 27, 13, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vivamus', null, 2.2, 6, 14, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('fusce lacus', 'Puce', 1.3, 20, 17, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('duis consequat', 'Pink', 4.2, 2, 15, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nisl aenean', 'Crimson', 1.8, 28, 15, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nunc proin', 'Aquamarine', 1.5, 1, 14, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eget tincidunt', 'Orange', 2.6, 22, 6, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('iaculis', 'Indigo', 3.5, 22, 8, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ultrices', 'Fuscia', 4.9, 8, 16, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sem sed', 'Yellow', 3.4, 29, 4, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('enim', 'Aquamarine', 4.1, 21, 8, 2014, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('magnis dis', 'Green', 2.9, 4, 18, 2012, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('orci', 'Orange', 4.5, 28, 8, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('felis eu', 'Pink', 2.1, 30, 8, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sociis natoque', 'Pink', 1.2, 18, 18, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aliquet at', 'Goldenrod', 3.0, 17, 11, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ante vel', 'Red', 2.8, 27, 19, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sapien', 'Maroon', 1.2, 16, 20, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('est', 'Fuscia', 3.1, 26, 13, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('justo', 'Crimson', 1.2, 18, 4, 2012, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('purus phasellus', 'Violet', 4.7, 15, 20, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mi', 'Yellow', 1.0, 25, 10, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('massa', 'Aquamarine', 3.5, 11, 2, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('integer', 'Blue', 1.9, 15, 11, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nulla ac', 'Goldenrod', 2.7, 7, 17, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('cum sociis', 'Goldenrod', 4.6, 24, 12, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('posuere', 'Indigo', 2.9, 8, 12, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('platea dictumst', 'Fuscia', 4.6, 2, 2, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('justo lacinia', 'Khaki', 1.4, 20, 2, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('amet cursus', 'Mauv', 2.6, 15, 7, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('est', 'Purple', 4.5, 25, 13, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nisl aenean', 'Khaki', 2.0, 1, 3, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mauris', 'Crimson', 1.0, 30, 15, 2012, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('habitasse', 'Maroon', 4.9, 13, 20, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('rutrum', 'Blue', 4.6, 17, 12, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sem fusce', 'Teal', 1.7, 6, 19, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('posuere cubilia', 'Aquamarine', 4.4, 1, 7, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('risus auctor', 'Indigo', 3.6, 15, 7, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('imperdiet sapien', null, 4.9, 5, 14, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('fusce consequat', null, 1.9, 19, 3, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eget', 'Teal', 0.6, 18, 3, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in purus', 'Turquoise', 3.6, 3, 2, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('malesuada in', 'Indigo', 1.2, 19, 6, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('hac', 'Maroon', 2.5, 6, 13, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('non ligula', 'Mauv', 3.0, 5, 15, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('at', 'Purple', 3.6, 30, 4, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('interdum', 'Pink', 1.4, 2, 5, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('phasellus id', 'Goldenrod', 3.0, 16, 9, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('consequat', 'Goldenrod', 3.9, 9, 13, 2017, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sit amet', null, 0.9, 12, 14, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('elit', 'Crimson', 3.5, 29, 17, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('gravida', 'Green', 2.0, 16, 15, 2016, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sem fusce', 'Violet', 3.7, 19, 1, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nunc purus', 'Mauv', 3.4, 13, 9, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nunc', 'Green', 3.4, 26, 13, 2015, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('congue', 'Khaki', 0.7, 22, 1, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ac consequat', null, 3.4, 15, 7, 2017, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('lectus in', 'Crimson', 1.8, 10, 4, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('eu', 'Crimson', 4.4, 2, 14, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('arcu', 'Mauv', 1.0, 19, 14, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('pulvinar lobortis', 'Maroon', 1.8, 14, 16, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('nam tristique', 'Fuscia', 1.2, 25, 20, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('urna ut', 'Orange', 4.5, 10, 8, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('interdum in', 'Puce', 2.4, 27, 5, 2013, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('interdum', 'Pink', 3.3, 19, 14, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('tempus vel', 'Green', 4.0, 30, 16, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('hac habitasse', 'Puce', 2.3, 17, 17, 2020, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('quam nec', 'Indigo', 2.4, 5, 3, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('aenean', 'Violet', 2.8, 1, 2, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('id', 'Indigo', 4.7, 8, 19, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('erat id', 'Indigo', 4.6, 5, 20, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('donec posuere', 'Purple', 0.7, 22, 10, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('duis', 'Yellow', 3.7, 5, 5, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('purus', 'Indigo', 4.7, 15, 1, 2015, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('mauris', 'Blue', 3.2, 28, 2, 2019, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('volutpat sapien', 'Purple', 3.9, 3, 3, 2018, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('pede', 'Crimson', 3.9, 24, 7, 2011, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('gravida', 'Turquoise', 4.4, 21, 4, 2018, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('cras', 'Turquoise', 2.7, 7, 12, 2010, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('in felis', 'Turquoise', 2.6, 30, 12, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('posuere', 'Indigo', 0.6, 27, 15, 2010, true);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('cum sociis', 'Crimson', 1.8, 1, 7, 2013, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('ridiculus mus', 'Goldenrod', 1.4, 30, 9, 2019, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('amet', 'Yellow', 0.9, 18, 16, 2012, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('magna', 'Khaki', 1.7, 18, 17, 2016, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('vivamus in', 'Turquoise', 1.2, 14, 3, 2011, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('sit amet', 'Puce', 2.1, 4, 6, 2020, false);
insert into ToyHistory (toyName, toyColor, workTime, childID, elvenID, yearProduced, delivered) values ('at', 'Fuscia', 1.1, 4, 12, 2016, true);
